### ISSUE TITLE
Tracking: Lending 0

### ISSUE THREAD

**Issue by ueco-jb** [securesecrets/shade#379]
- [ ] refactor smart contracts
  - [ ] lend token 
    - [x] snip20 as collateral / borrowed #366
    - [ ] tests #368 
  - [ ] lend market #376  
    - [ ] code #378 
    - [ ] oracle queries
    - [ ] tests
  - [ ] credit agency
  - [ ] queries for public internal data that aggregate into a single query
  - [ ] create lending utils crate #365 
- [ ] documentation
